name: Build & Release APK

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '21'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.0'
          channel: 'stable'

      - name: Get dependencies
        run: flutter pub get

      - name: Build APK
        run: flutter build apk --release --no-tree-shake-icons

      - name: Rename APK
        run: |
          VERSION=${GITHUB_REF_NAME:-manual}
          mv build/app/outputs/flutter-apk/app-release.apk \
             build/app/outputs/flutter-apk/TunVPN-${VERSION}.apk

      - name: Create GitHub Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v2
        with:
          name: "TunVPN ${{ github.ref_name }}"
          files: build/app/outputs/flutter-apk/TunVPN-*.apk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload APK Artifact
        if: github.event_name == 'workflow_dispatch'
        uses: actions/upload-artifact@v4
        with:
          name: TunVPN-debug-build
          path: build/app/outputs/flutter-apk/TunVPN-*.apk
          retention-days: 7
